DRY_RUN = True

ESTIMATION_ORDERBOOK = 3

MAX_TRIES_ORDERBOOK = 5

WAIT_BETWEEN_ORDER = 10

MIN_PROFIT_THRESHOLD = 0.1

ASSETS = [
    "XRP", "LTC", "ADA", "TRX", "BNB", "LINK", "DOT", "MATIC", "ATOM", "DOGE"
]

BLACKLIST = []

AUTO_BLACKLIST_THRESHOLD = 3
